version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_LOGIN
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - $MONGO_PORT:27017
    volumes:
      - ./docker-data/mongo-data:/data/db
      
  mongo-test:
    image: mongo
    container_name: mongo-test
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_LOGIN
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - $MONGO_PORT_TEST:27017